/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/schedules/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 장소 직접 추가
         * @description 로그인한 사용자가 새로운 커스텀 장소(이름, 시간, 참고링크, 순서)를 추가합니다.
         */
        post: operations["createCustomPlace"];
        /**
         * 장소 정보 삭제
         * @description 로그인한 사용자가 선택한 장소를 일정에서 삭제합니다.
         */
        delete: operations["deletePlace"];
        options?: never;
        head?: never;
        /**
         * 장소 정보 수정
         * @description 로그인한 사용자가 장소명, 시간, 참고링크를 수정합니다. 커스텀 장소, ai 일정 모두 수정 가능
         */
        patch: operations["updatePlace"];
        trace?: never;
    };
    "/api/v1/schedules/ai": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * AI 일정 생성
         * @description 사용자의 그룹별 여행지, 여행 스타일에 따른 AI 추천 일정을 생성합니다.
         */
        post: operations["generateAiScheduleSimple"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedules/ai/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * AI 일정 수정 요청
         * @description 사용자의 피드백 프롬프트(예: '더 느긋하게')를 받아 AI 제안 일정을 반환합니다. (DB 미반영)
         */
        post: operations["suggestAiScheduleUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedules/ai/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * AI 제안 일정 확정
         * @description AI가 제안한 수정 일정(AiScheduleUpdateResDto)을 최종 선택하여 DB를 갱신합니다.
         */
        post: operations["applyAiScheduleUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/places/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 장소 반응(좋아요/별로예요) 통계 조회
         * @description 장소의 좋아요/별로예요 개수 및 투표율을 조회합니다.
         */
        get: operations["getTravelVote"];
        put?: never;
        /**
         * 장소 투표(좋아요/별로예요) 토글
         * @description 로그인한 사용자가 좋아요/별로예요 토글로 투표합니다.
         */
        post: operations["toggleVote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/login/test-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 테스트 계정 로그인
         * @description test 계정 로그인 API입니다.
         */
        post: operations["testLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/login/reissue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 리프레시 토큰으로 액세스 토큰 재발급
         * @description HttpOnly 쿠키에 있는 refreshToken으로 accessToken을 재발급합니다.
         */
        post: operations["getAccessTokenByRefreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/login/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 쿠키 토큰 삭제
         * @description 쿠키에 들어있는 토큰 삭제로 로그아웃시 사용 가능
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 그룹 상세 정보 조회
         * @description 그룹에 참여한 사용자가 그룹 상세 정보를 조회합니다.
         */
        get: operations["getDetailGroup"];
        put?: never;
        /**
         * 그룹 생성
         * @description 로그인한 팀장이 그룹을 생성합니다.
         */
        post: operations["createGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/styles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 팀장 내 성향 카드 조회
         * @description 팀장 개인의 여행 스타일을 분석하여 내 성향 카드를 조회합니다.
         */
        get: operations["getLeaderStyleCard"];
        put?: never;
        /**
         * 팀장 여행 스타일 입력
         * @description 로그인한 사용자(팀장)가 해당 그룹의 여행 스타일을 입력합니다.
         */
        post: operations["createLeaderStyle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/styles/guest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 게스트 여행 스타일 입력
         * @description 게스트가 자신의 여행 스타일을 입력합니다.
         */
        post: operations["createGuestStyle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 게스트 초대
         * @description 로그인한 팀장이 링크를 복사하여 게스트를 초대합니다.
         *      게스트가 해당 링크로 참여시 해당 그룹의 멤버로 자동으로 등록됨
         */
        post: operations["inviteGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/roulette": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 룰렛
         * @description 그룹 id로 판별하여 벌칙 생성 후 룰렛 돌리기
         */
        post: operations["createRoulette"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/quiz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로컬 퀴즈 생성
         * @description GEMINI API로 퀴즈 생성 요청을 보냅니다. 약 8초 소요됩니다.
         */
        post: operations["createQuiz"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/quiz/answer/{gameId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로컬 퀴즈 답 제출
         * @description 퀴즈 답을 제출하여 정답 여부를 조회합니다.
         */
        post: operations["submitQuiz"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 멤버 리스트 조회
         * @description 게임을 하기 위한 그룹별 멤버 리스트를 조회합니다.
         */
        post: operations["getGameMembers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/ladder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 사다리 타기
         * @description 그룹 id로 판별하여 벌칙 작성 후 사다리 타기
         */
        post: operations["createLadder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 지출 기록 생성
         * @description 그룹에 포함된 사용자가 지출 기록을 생성합니다.
         */
        post: operations["createExpense"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/efforts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 수고 회고 생성
         * @description 특정 멤버에게 전달할 수고 가치 금액과 한마디를 입력하여 제출합니다.
         */
        post: operations["createEffort"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/effort-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 수고 항목 리스트 조회
         * @description 그룹 내 등록된 기본/커스텀 수고 항목 목록을 조회합니다.
         */
        get: operations["getEffortItems"];
        put?: never;
        /**
         * 수고 항목 직접 추가
         * @description 사용자가 직접 새로운 수고 항목을 추가합니다.
         */
        post: operations["createEffortItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 댓글 전체 조회
         * @description 로그인한 사용자가 상세 일정에 달린 댓글 리스트를 조회합니다.
         */
        get: operations["getComments"];
        put?: never;
        /**
         * 댓글 생성
         * @description 로그인한 사용자가 상세 일정에 댓글을 답니다.
         */
        post: operations["createComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 정보 조회
         * @description 로그인한 사용자가 자신의 계정 정보를 조회합니다. (본인만 조회 가능, 이메일 포함)
         */
        get: operations["getUserInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 내 정보 수정
         * @description 로그인한 사용자가 닉네임, 고유 색상을 수정합니다.
         */
        patch: operations["updateUserInfo"];
        trace?: never;
    };
    "/api/v1/users/agree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 동의 항목 여부 수정
         * @description 로그인한 사용자가 동의 항목 여부를 수정합니다.
         */
        patch: operations["updateUserAgree"];
        trace?: never;
    };
    "/api/v1/schedules/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 일정 확정
         * @description 일정을 확정합니다. 그룹 상태가 CONFIRMED로 변경됩니다.
         */
        patch: operations["confirmSchedule"];
        trace?: never;
    };
    "/api/v1/notifications/{notificationId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 알림 읽음 처리
         * @description 사용자가 상세 알림을 읽음 처리합니다.
         */
        patch: operations["readNotification"];
        trace?: never;
    };
    "/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["test"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 타임라인 조회
         * @description 그룹에 참여한 사용자가 타임라인 리스트를 조회합니다.
         */
        get: operations["getTimeLine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/timeline/remaining": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 남은 일정 조회
         * @description 그룹에 참여한 사용자가 남은 일정 리스트를 조회합니다.
         */
        get: operations["getRemainingSchedule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedules/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 그룹별 상세 일정 조회
         * @description 로그인한 사용자가 그룹별 상세 일정 정보를 조회합니다.
         */
        get: operations["getDetailSchedule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedules/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 그룹별 전체 일정 조회
         * @description 로그인한 사용자가 그룹별 전체 일정을 조회합니다.
         */
        get: operations["getAllSchedule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 알림 전체 목록 조회
         * @description 사용자가 알림 전체 리스트를 조회합니다.
         */
        get: operations["getNotificationList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SSE 구독
         * @description SSE 구독 생성, 로딩중 화면이 정상입니다.
         */
        get: operations["subscribe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/login/kakao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 카카오 로그인
         * @description 카카오 로그인 콜백 api입니다.
         */
        get: operations["kakaoCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 그룹 정보 요약 조회
         * @description 비로그인 사용자에게 그룹 요약 정보를 보여줍니다.
         */
        get: operations["getSummaryGroup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/styles/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 팀장 그룹 정보 리스트 조회
         * @description 팀장이 생성했거나 속해있는 전체 그룹 요약 목록(groupId, title, startDate, endDate)을 조회합니다.
         */
        get: operations["getLeaderGroupList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 그룹 전체 정보 조회
         * @description 로그인한 팀장(카카오 사용자)이 참여한 내가 참여한 그룹 전체 정보 리스트를 조회합니다.
         */
        get: operations["getMyGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expenses/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 지출 기록 전체 조회
         * @description 그룹에 포함된 사용자가 지출 기록 리스트를 조회합니다.
         */
        get: operations["getAllExpenses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/efforts/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 최종 수고 결과 조회
         * @description 특정 멤버가 전달받은 수고 보상 금액의 중간값과 친구들의 한마디 리스트를 조회합니다.
         */
        get: operations["getEffortResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/effort-items/{effortItemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 수고 항목 삭제
         * @description 직접 추가했던 커스텀 수고 항목을 삭제합니다.
         */
        delete: operations["deleteEffortItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TravelPlaceCreateReqDto: {
            /** Format: int64 */
            travelDayId?: number;
            /** Format: int32 */
            scheduleOrder?: number;
            customName?: string;
            visitTime?: string;
            memoUrl?: string;
        };
        ApiResTemplateTravelPlaceInfoResDto: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            data?: components["schemas"]["TravelPlaceInfoResDto"];
        };
        TravelPlaceInfoResDto: {
            /** Format: int64 */
            travelPlaceId?: number;
            contentId?: string;
            visitTime?: string;
            /** Format: int32 */
            scheduleOrder?: number;
            placeType?: string;
            reason?: string;
            name?: string;
            address?: string;
            imageUrl?: string;
            memoUrl?: string;
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
            /** Format: double */
            distanceFromPreviousKm?: number;
        };
        ApiResTemplateTravelScheduleResDto: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            data?: components["schemas"]["TravelScheduleResDto"];
        };
        Day: {
            /** Format: int32 */
            dayNumber?: number;
            /** Format: double */
            totalDistanceKm?: number;
            places?: components["schemas"]["Place"][];
        };
        Place: {
            /** Format: int64 */
            travelPlaceId?: number;
            contentId?: string;
            visitTime?: string;
            name?: string;
            address?: string;
            imageUrl?: string;
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
            /** Format: int32 */
            scheduleOrder?: number;
            placeType?: string;
            reason?: string;
            /** Format: double */
            distanceFromPreviousKm?: number;
            memoUrl?: string;
        };
        TravelScheduleResDto: {
            /** Format: int64 */
            travelId?: number;
            days?: components["schemas"]["Day"][];
        };
        AiScheduleUpdateReqDto: {
            /** Format: int64 */
            groupId?: number;
            /** Format: int32 */
            dayNum?: number;
            prompt?: string;
        };
        AiScheduleUpdateResDto: {
            summaryTitle?: string;
            /** Format: int32 */
            dayNumber?: number;
            originalPlace?: components["schemas"]["OriginalPlaceDto"];
            newPlaces?: components["schemas"]["NewPlaceDto"][];
        };
        ApiResTemplateAiScheduleUpdateResDto: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            data?: components["schemas"]["AiScheduleUpdateResDto"];
        };
        NewPlaceDto: {
            contentId?: string;
            visitTime?: string;
            placeType?: string;
            reason?: string;
        };
        OriginalPlaceDto: {
            contentId?: string;
            visitTime?: string;
            placeName?: string;
        };
        VoteReqDto: {
            /** @enum {string} */
            voteStatus: "LIKE" | "DISLIKE";
        };
        ApiResTemplateVoteResDto: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            data?: components["schemas"]["VoteResDto"];
        };
        VoteResDto: {
            /** Format: int64 */
            likeCount?: number;
            /** Format: int32 */
            likePercentage?: number;
            /** Format: int64 */
            dislikeCount?: number;
            /** Format: int32 */
            dislikePercentage?: number;
            /** Format: int64 */
            totalParticipantCount?: number;
            /** Format: int32 */
            totalGroupMemberCount?: number;
            /** @enum {string} */
            voteStatus?: "LIKE" | "DISLIKE";
        };
        ApiResTemplateLoginInfoResDto: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            data?: components["schemas"]["LoginInfoResDto"];
        };
        LoginInfoResDto: {
            /** Format: int64 */
            userId?: number;
        };
        ApiResTemplateString: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            data?: string;
        };
        GroupCreateReqDto: {
            title?: string;
            /** @enum {string} */
            destination?: "BUSAN" | "GANGNEUNG" | "GYEONGJU" | "YEOSU" | "JEONJU" | "SOKCHO";
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
            /** Format: int32 */
            memberCount?: number;
            /** @enum {string} */
            transportType?: "RENT" | "PUBLIC";
        };
        ApiResTemplateGroupInfoResDto: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            data?: components["schemas"]["GroupInfoResDto"];
        };
        GroupInfoResDto: {
            /** Format: int64 */
            groupId?: number;
            title?: string;
            /** @enum {string} */
            destination?: "BUSAN" | "GANGNEUNG" | "GYEONGJU" | "YEOSU" | "JEONJU" | "SOKCHO";
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
            /** Format: int32 */
            currentMemberCount?: number;
            /** Format: int32 */
            memberCount?: number;
            /** @enum {string} */
            transportType?: "RENT" | "PUBLIC";
            groupLink?: string;
            dDay?: string;
            members?: components["schemas"]["GroupMemberInfoResDto"][];
            /** @enum {string} */
            groupStatus?: "PLANNING" | "CONFIRMED" | "COMPLETED";
        };
        GroupMemberInfoResDto: {
            /** Format: int64 */
            groupMemberId?: number;
            memberName?: string;
            /** @enum {string} */
            memberColor?: "BLUE" | "PURPLE" | "SKYBLUE" | "ORANGE";
            /** @enum {string} */
            memberRole?: "LEADER" | "MEMBER";
            /** @enum {string} */
            memberStatus?: "PENDING" | "BEFORE_PREFERENCE" | "COMPLETED";
        };
        StyleReqDto: {
            /** @enum {string} */
            budgetType: "ECONOMICAL" | "MODERATE" | "LUXURY";
            /** @enum {string} */
            foodType: "KOREAN" | "JAPANESE" | "CHINESE";
            /** Format: int32 */
            activityIntensity: number;
        };
        ApiResTemplateStyleInfoResDto: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            data?: components["schemas"]["StyleInfoResDto"];
        };
        StyleInfoResDto: {
            /** Format: int64 */
            styleId?: number;
            /** Format: int64 */
            groupId?: number;
            /** Format: int64 */
            groupMemberId?: number;
            /** @enum {string} */
            budgetType?: "ECONOMICAL" | "MODERATE" | "LUXURY";
            /** @enum {string} */
            foodType?: "KOREAN" | "JAPANESE" | "CHINESE";
            /** Format: int32 */
            activityIntensity?: number;
        };
        GroupGuestInfoReqDto: {
            memberName?: string;
            /** @enum {string} */
            memberColor?: "BLUE" | "PURPLE" | "SKYBLUE" | "ORANGE";
        };
        ApiResTemplateGroupGuestJoinResDto: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            data?: components["schemas"]["GroupGuestJoinResDto"];
        };
        GroupGuestJoinResDto: {
            /** Format: int64 */
            groupMemberId?: number;
            memberName?: string;
            /** @enum {string} */
            memberColor?: "BLUE" | "PURPLE" | "SKYBLUE" | "ORANGE";
            group?: components["schemas"]["GroupInfoResDto"];
        };
        GameCreateReqDto: {
            penalty: string;
        };
        GameMemberInfoResDto: {
            /** Format: int64 */
            groupMemberId?: number;
            nickname?: string;
            result?: string;
        };
        GameResultResDto: {
            /** Format: int64 */
            gameId?: number;
            /** Format: int64 */
            groupId?: number;
            /** @enum {string} */
            gameType?: "LADDER" | "ROULETTE" | "QUIZ";
            penalty?: string;
            result?: components["schemas"]["GameMemberInfoResDto"][];
        };
        ApiResTemplateQuizOptionListResDto: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            data?: components["schemas"]["QuizOptionListResDto"];
        };
        QuizOptionInfoResDto: {
            option?: string;
            content?: string;
        };
        QuizOptionListResDto: {
            /** Format: int64 */
            gameId?: number;
            /** Format: int64 */
            groupId?: number;
            question?: string;
            options?: components["schemas"]["QuizOptionInfoResDto"][];
        };
        QuizAnswerReqDto: {
            selectedOption: string;
        };
        ApiResTemplateQuizAnswerResDto: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            data?: components["schemas"]["QuizAnswerResDto"];
        };
        QuizAnswerResDto: {
            correct?: boolean;
            selectedOption?: string;
            correctOption?: string;
            explanation?: string;
        };
        GameMemberListResDto: {
            /** Format: int64 */
            groupMemberId?: number;
            memberName?: string;
        };
        ExpenseParticipantReqDto: {
            /** Format: int64 */
            groupMemberId?: number;
            isIncluded: boolean;
        };
        ExpensePayerReqDto: {
            /** Format: int64 */
            groupMemberId?: number;
        };
        ExpenseReqDto: {
            /** Format: int64 */
            groupId: number;
            amount: number;
            /** @enum {string} */
            category?: "MEAL" | "GAS" | "ACCOMMODATION" | "CAFE" | "OTHER";
            /** Format: date */
            expenseDate?: string;
            payers: components["schemas"]["ExpensePayerReqDto"][];
            participants: components["schemas"]["ExpenseParticipantReqDto"][];
        };
        ApiResTemplateExpenseInfoResDto: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            data?: components["schemas"]["ExpenseInfoResDto"];
        };
        ExpenseInfoResDto: {
            /** Format: int64 */
            expenseId?: number;
            amount?: number;
            /** @enum {string} */
            category?: "MEAL" | "GAS" | "ACCOMMODATION" | "CAFE" | "OTHER";
            /** Format: date */
            expenseDate?: string;
            payerName?: string;
            /** Format: int32 */
            participantCount?: number;
            payers?: components["schemas"]["ExpensePayerResDto"][];
            participants?: components["schemas"]["ExpenseParticipantResDto"][];
        };
        ExpenseParticipantResDto: {
            /** Format: int64 */
            expenseParticipantId?: number;
            /** Format: int64 */
            groupMemberId?: number;
            isIncluded?: boolean;
        };
        ExpensePayerResDto: {
            /** Format: int64 */
            expensePayerId?: number;
            /** Format: int64 */
            groupMemberId?: number;
        };
        EffortReqDto: {
            /** Format: int64 */
            groupId: number;
            /** Format: int64 */
            targetMemberId?: number;
            /** Format: int64 */
            effortAmount?: number;
            comment?: string;
            /** Format: int64 */
            effortItemId: number;
        };
        ApiResTemplateEffortInfoResDto: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            data?: components["schemas"]["EffortInfoResDto"];
        };
        EffortInfoResDto: {
            /** Format: int64 */
            effortId?: number;
            /** Format: int64 */
            writerMemberId?: number;
            /** Format: int64 */
            targetMemberId?: number;
            targetMemberName?: string;
            /** Format: int64 */
            effortItemId?: number;
            /** Format: int64 */
            effortAmount?: number;
            comment?: string;
        };
        EffortItemReqDto: {
            /** @enum {string} */
            itemCategory: "DRIVING" | "RESERVATION" | "ETC";
            title?: string;
        };
        ApiResTemplateEffortItemResDto: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            data?: components["schemas"]["EffortItemResDto"];
        };
        EffortItemResDto: {
            /** Format: int64 */
            effortItemId?: number;
            title?: string;
            isCustom?: boolean;
            memberList?: components["schemas"]["GameMemberListResDto"][];
        };
        CommentCreateReqDto: {
            content: string;
        };
        ApiResTemplateCommentInfoResDto: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            data?: components["schemas"]["CommentInfoResDto"];
        };
        CommentInfoResDto: {
            /** Format: int64 */
            commentId?: number;
            /** Format: int64 */
            userId?: number;
            nickname?: string;
            /** @enum {string} */
            memberColor?: "BLUE" | "PURPLE" | "SKYBLUE" | "ORANGE";
            profileImageUrl?: string;
            content?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        UserInfoUpdateReqDto: {
            nickname: string;
            /** @enum {string} */
            memberColor: "BLUE" | "PURPLE" | "SKYBLUE" | "ORANGE";
        };
        ApiResTemplateUserInfoResDto: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            data?: components["schemas"]["UserInfoResDto"];
        };
        UserInfoResDto: {
            /** Format: int64 */
            userId?: number;
            nickname?: string;
            email?: string;
            profileImageUrl?: string;
            /** @enum {string} */
            socialType?: "KAKAO" | "LOCAL";
            /** @enum {string} */
            userRole?: "LEADER" | "GUEST";
            /** @enum {string} */
            memberColor?: "BLUE" | "PURPLE" | "SKYBLUE" | "ORANGE";
            notificationAgree?: components["schemas"]["UserNotificationAgreeResDto"];
        };
        UserNotificationAgreeResDto: {
            notifyComments?: boolean;
            notifyReminders?: boolean;
            notifySettlement?: boolean;
            notifyMarketing?: boolean;
        };
        UserAgreeUpdateReqDto: {
            notifyComments: boolean;
            notifyReminders: boolean;
            notifySettlement: boolean;
            notifyMarketing: boolean;
        };
        TravelPlaceUpdateReqDto: {
            customName?: string;
            /** Format: int32 */
            scheduleOrder?: number;
            visitTime?: string;
            memoUrl?: string;
        };
        ApiResTemplateGroupStatusResDto: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            data?: components["schemas"]["GroupStatusResDto"];
        };
        GroupStatusResDto: {
            /** Format: int64 */
            groupId?: number;
            title?: string;
            /** @enum {string} */
            destination?: "BUSAN" | "GANGNEUNG" | "GYEONGJU" | "YEOSU" | "JEONJU" | "SOKCHO";
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
            groupLink?: string;
            /** @enum {string} */
            groupStatus?: "PLANNING" | "CONFIRMED" | "COMPLETED";
        };
        ApiResTemplateNotificationResDto: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            data?: components["schemas"]["NotificationResDto"];
        };
        NotificationResDto: {
            /** Format: int64 */
            notificationId?: number;
            /** Format: int64 */
            userId?: number;
            /** Format: int64 */
            guestGroupMemberId?: number;
            /** @enum {string} */
            type?: "RETROSPECT_COMPLETE" | "GROUP_JOIN_COMPLETE";
            title?: string;
            content?: string;
            /** Format: int64 */
            targetId?: number;
            isRead?: boolean;
            /** Format: date-time */
            notificationCreatedAt?: string;
            /** Format: int64 */
            totalCount?: number;
        };
        ApiResTemplateUserTimelineResDto: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            data?: components["schemas"]["UserTimelineResDto"];
        };
        TimelineItemDto: {
            /** Format: int64 */
            id?: number;
            title?: string;
            /** Format: date-time */
            time?: string;
            category?: string;
            description?: string;
        };
        UserTimelineResDto: {
            /** Format: int32 */
            currentDay?: number;
            /** Format: int32 */
            totalExpense?: number;
            items?: components["schemas"]["TimelineItemDto"][];
        };
        ApiResTemplateUserScheduleResDto: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            data?: components["schemas"]["UserScheduleResDto"];
        };
        RemainingScheduleResDto: {
            /** Format: int64 */
            travelPlaceId?: number;
            /** Format: date-time */
            time?: string;
            placeName?: string;
            category?: string;
        };
        UserScheduleResDto: {
            /** Format: int64 */
            groupId?: number;
            scheduleStatus?: string;
            groupTitle?: string;
            /** Format: int32 */
            currentDay?: number;
            currentStatus?: string;
            /** Format: int32 */
            totalExpense?: number;
            todaySchedules?: components["schemas"]["RemainingScheduleResDto"][];
        };
        ApiResTemplateListNotificationResDto: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            data?: components["schemas"]["NotificationResDto"][];
        };
        SseEmitter: {
            /** Format: int64 */
            timeout?: number;
        };
        ApiResTemplateGroupSummaryInfoResDto: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            data?: components["schemas"]["GroupSummaryInfoResDto"];
        };
        GroupSummaryInfoResDto: {
            inviterName?: string;
            title?: string;
            /** @enum {string} */
            destination?: "BUSAN" | "GANGNEUNG" | "GYEONGJU" | "YEOSU" | "JEONJU" | "SOKCHO";
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
            /** Format: int32 */
            memberCount?: number;
            duration?: string;
        };
        ApiResTemplateMyStyleCardResDto: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            data?: components["schemas"]["MyStyleCardResDto"];
        };
        MyStyleCardResDto: {
            /** Format: int64 */
            styleId?: number;
            /** Format: int64 */
            groupId?: number;
            /** Format: int64 */
            groupMemberId?: number;
            dnaTitle?: string;
            dnaDescription?: string;
            tags?: string[];
            activityLevelText?: string;
            budgetStyleText?: string;
            preferredFoodText?: string;
            /** @enum {string} */
            budgetType?: "ECONOMICAL" | "MODERATE" | "LUXURY";
            /** @enum {string} */
            foodType?: "KOREAN" | "JAPANESE" | "CHINESE";
            /** Format: int32 */
            activityIntensity?: number;
        };
        ApiResTemplateListStyleGroupListResDto: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            data?: components["schemas"]["StyleGroupListResDto"][];
        };
        StyleGroupListResDto: {
            /** Format: int64 */
            groupId?: number;
            title?: string;
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
        };
        ApiResTemplateGroupListResDto: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            data?: components["schemas"]["GroupListResDto"];
        };
        GroupListResDto: {
            ongoingGroups?: components["schemas"]["GroupInfoResDto"][];
            pastGroups?: components["schemas"]["GroupInfoResDto"][];
        };
        ApiResTemplateExpenseListResDto: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            data?: components["schemas"]["ExpenseListResDto"];
        };
        ExpenseListResDto: {
            totalAmount?: number;
            expenseInfoResDtos?: components["schemas"]["ExpenseInfoResDto"][];
        };
        ApiResTemplateEffortResultResDto: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            data?: components["schemas"]["EffortResultResDto"];
        };
        EffortResultResDto: {
            /** Format: int64 */
            targetMemberId?: number;
            targetMemberName?: string;
            /** Format: int64 */
            totalRewardAmount?: number;
            /** Format: int32 */
            evaluatorCount?: number;
            comments?: string[];
        };
        ApiResTemplateListEffortItemResDto: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            data?: components["schemas"]["EffortItemResDto"][];
        };
        ApiResTemplateCommentListResDto: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            data?: components["schemas"]["CommentListResDto"];
        };
        CommentListResDto: {
            /** Format: int64 */
            commentCount?: number;
            comments?: components["schemas"]["CommentInfoResDto"][];
        };
        ApiResTemplateVoid: {
            /** Format: int32 */
            status?: number;
            code?: string;
            message?: string;
            data?: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createCustomPlace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                guestAccessToken?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TravelPlaceCreateReqDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateTravelPlaceInfoResDto"];
                };
            };
        };
    };
    deletePlace: {
        parameters: {
            query: {
                travelPlaceId: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                guestAccessToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateString"];
                };
            };
        };
    };
    updatePlace: {
        parameters: {
            query: {
                travelPlaceId: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                guestAccessToken?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TravelPlaceUpdateReqDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateTravelPlaceInfoResDto"];
                };
            };
        };
    };
    generateAiScheduleSimple: {
        parameters: {
            query: {
                groupId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateTravelScheduleResDto"];
                };
            };
        };
    };
    suggestAiScheduleUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                guestAccessToken?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiScheduleUpdateReqDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateAiScheduleUpdateResDto"];
                };
            };
        };
    };
    applyAiScheduleUpdate: {
        parameters: {
            query: {
                groupId: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                guestAccessToken?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiScheduleUpdateResDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateTravelScheduleResDto"];
                };
            };
        };
    };
    getTravelVote: {
        parameters: {
            query: {
                travelPlaceId: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                guestAccessToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateVoteResDto"];
                };
            };
        };
    };
    toggleVote: {
        parameters: {
            query: {
                travelPlaceId: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                guestAccessToken?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoteReqDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateVoteResDto"];
                };
            };
        };
    };
    testLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateLoginInfoResDto"];
                };
            };
        };
    };
    getAccessTokenByRefreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refreshToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateLoginInfoResDto"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refreshToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateString"];
                };
            };
        };
    };
    getDetailGroup: {
        parameters: {
            query: {
                groupId: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                guestAccessToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateGroupInfoResDto"];
                };
            };
        };
    };
    createGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupCreateReqDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateGroupInfoResDto"];
                };
            };
        };
    };
    getLeaderStyleCard: {
        parameters: {
            query: {
                groupId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateMyStyleCardResDto"];
                };
            };
        };
    };
    createLeaderStyle: {
        parameters: {
            query: {
                groupId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StyleReqDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateStyleInfoResDto"];
                };
            };
        };
    };
    createGuestStyle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                guestAccessToken?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StyleReqDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateStyleInfoResDto"];
                };
            };
        };
    };
    inviteGroup: {
        parameters: {
            query: {
                groupLink: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupGuestInfoReqDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateGroupGuestJoinResDto"];
                };
            };
        };
    };
    createRoulette: {
        parameters: {
            query: {
                groupId: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                guestAccessToken?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GameCreateReqDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GameResultResDto"];
                };
            };
        };
    };
    createQuiz: {
        parameters: {
            query: {
                groupId: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                guestAccessToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateQuizOptionListResDto"];
                };
            };
        };
    };
    submitQuiz: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: number;
            };
            cookie?: {
                guestAccessToken?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizAnswerReqDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateQuizAnswerResDto"];
                };
            };
        };
    };
    getGameMembers: {
        parameters: {
            query: {
                groupId: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                guestAccessToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GameMemberListResDto"][];
                };
            };
        };
    };
    createLadder: {
        parameters: {
            query: {
                groupId: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                guestAccessToken?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GameCreateReqDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GameResultResDto"];
                };
            };
        };
    };
    createExpense: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                guestAccessToken?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseReqDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateExpenseInfoResDto"];
                };
            };
        };
    };
    createEffort: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                guestAccessToken?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EffortReqDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateEffortInfoResDto"];
                };
            };
        };
    };
    getEffortItems: {
        parameters: {
            query: {
                groupId: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                guestAccessToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateListEffortItemResDto"];
                };
            };
        };
    };
    createEffortItem: {
        parameters: {
            query: {
                groupId: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                guestAccessToken?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EffortItemReqDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateEffortItemResDto"];
                };
            };
        };
    };
    getComments: {
        parameters: {
            query: {
                travelPlaceId: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                guestAccessToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateCommentListResDto"];
                };
            };
        };
    };
    createComment: {
        parameters: {
            query: {
                travelPlaceId: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                guestAccessToken?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentCreateReqDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateCommentInfoResDto"];
                };
            };
        };
    };
    getUserInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateUserInfoResDto"];
                };
            };
        };
    };
    updateUserInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserInfoUpdateReqDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateUserInfoResDto"];
                };
            };
        };
    };
    updateUserAgree: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserAgreeUpdateReqDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateUserInfoResDto"];
                };
            };
        };
    };
    confirmSchedule: {
        parameters: {
            query: {
                groupId: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                guestAccessToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateGroupStatusResDto"];
                };
            };
        };
    };
    readNotification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notificationId: number;
            };
            cookie?: {
                guestAccessToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateNotificationResDto"];
                };
            };
        };
    };
    test: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    getTimeLine: {
        parameters: {
            query: {
                groupId: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                guestAccessToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateUserTimelineResDto"];
                };
            };
        };
    };
    getRemainingSchedule: {
        parameters: {
            query: {
                groupId: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                guestAccessToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateUserScheduleResDto"];
                };
            };
        };
    };
    getDetailSchedule: {
        parameters: {
            query: {
                travelPlaceId: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                guestAccessToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateTravelPlaceInfoResDto"];
                };
            };
        };
    };
    getAllSchedule: {
        parameters: {
            query: {
                groupId: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                guestAccessToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateTravelScheduleResDto"];
                };
            };
        };
    };
    getNotificationList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                guestAccessToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateListNotificationResDto"];
                };
            };
        };
    };
    subscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                guestAccessToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    kakaoCallback: {
        parameters: {
            query: {
                code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateLoginInfoResDto"];
                };
            };
        };
    };
    getSummaryGroup: {
        parameters: {
            query: {
                groupLink: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateGroupSummaryInfoResDto"];
                };
            };
        };
    };
    getLeaderGroupList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateListStyleGroupListResDto"];
                };
            };
        };
    };
    getMyGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateGroupListResDto"];
                };
            };
        };
    };
    getAllExpenses: {
        parameters: {
            query: {
                groupId: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                guestAccessToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateExpenseListResDto"];
                };
            };
        };
    };
    getEffortResult: {
        parameters: {
            query: {
                groupId: number;
                targetMemberId: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                guestAccessToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateEffortResultResDto"];
                };
            };
        };
    };
    deleteEffortItem: {
        parameters: {
            query: {
                groupId: number;
            };
            header?: never;
            path: {
                effortItemId: number;
            };
            cookie?: {
                guestAccessToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResTemplateVoid"];
                };
            };
        };
    };
}
