import clsx from 'clsx';
import { extendTailwindMerge } from 'tailwind-merge';

import type { ClassValue } from 'clsx';

const twMerge = extendTailwindMerge({
  extend: {
    classGroups: {
      'font-size': [
        {
          text: [
            'display-base',
            'display-sm',
            'heading-2xl',
            'heading-xl',
            'heading-lg',
            'heading-base',
            'heading-sm',
            'heading-xs',
            'body-xl',
            'body-lg',
            'body-base',
            'body-sm',
            'body-xs',
            'detail-lg',
            'detail-base',
            'detail-sm',
            'detail-xs',
          ],
        },
      ],
      'text-color': [
        {
          text: [
            // text tokens
            'text-basic',
            'text-basic-inverse',
            'text-subtle',
            'text-subtler',
            'text-disabled',
            'text-disabled-on',
            'text-primary',
            'text-secondary',
            'text-tertiary',
            'text-error',
            'text-warning',
            'text-success',
            'text-primary-500',
          ],
        },
      ],
      'border-color': [
        {
          border: [
            'border-transparency',
            'border-disabled',
            'border-gray-light',
            'border-gray',
            'border-gray-dark',
            'border-gray-darker',
            'border-primary',
            'border-primary-light',
            'border-secondary',
            'border-secondary-light',
            'border-tertiary',
            'border-tertiary-light',
            'border-error',
            'border-error-light',
            'border-warning',
            'border-warning-light',
            'border-success',
            'border-success-light',
            'button-secondary-border',
            'button-tertiary-border',
            'button-text-border',
            'input-border',
            'input-border-active',
            'input-border-error',
            'input-border-disabled',
          ],
        },
      ],
      'ring-color': [
        {
          ring: [
            'border-transparency',
            'border-disabled',
            'border-gray-light',
            'border-gray',
            'border-gray-dark',
            'border-gray-darker',
            'border-primary',
            'border-primary-light',
            'border-secondary',
            'border-secondary-light',
            'border-tertiary',
            'border-tertiary-light',
            'border-error',
            'border-error-light',
            'border-warning',
            'border-warning-light',
            'border-success',
            'border-success-light',
          ],
        },
      ],
      'bg-color': [
        {
          bg: [
            'bg-white',
            'bg-gray-subtle',
            'bg-gray-subtler',
            'bg-inverse',
            'bg-inverse-subtle',
            'bg-inverse-subtler',
            'bg-dim',
            'surface-white',
            'surface-transparency',
            'surface-inverse',
            'surface-gray-subtler',
            'surface-gray-subtle',
            'surface-disabled',
            'surface-primary-subtler',
            'surface-secondary-subtler',
            'surface-point-subtler',
            'surface-success-subtler',
            'surface-warning-subtler',
            'surface-error-subtler',
            'action-white',
            'action-gray-light',
            'action-primary',
            'action-primary-hover',
            'action-primary-pressed',
            'action-primary-selected',
            'action-primary-active',
            'action-tag-primary',
            'action-tag-secondary',
            'action-tag-tertiary',
            'action-secondary',
            'action-secondary-on',
            'action-secondary-on-selected',
            'action-secondary-hover',
            'action-secondary-pressed',
            'action-secondary-selected',
            'action-secondary-active',
            'action-disabled',
            'button-primary-fill',
            'button-primary-fill-hover',
            'button-primary-fill-focus',
            'button-primary-fill-pressed',
            'button-secondary-fill',
            'button-secondary-fill-hover',
            'button-secondary-fill-pressed',
            'button-tertiary-fill',
            'button-tertiary-fill-hover',
            'button-tertiary-fill-pressed',
            'button-text-fill',
            'button-text-fill-hover',
            'button-text-fill-pressed',
            'button-disabled-fill',
            'input-surface',
            'input-surface-disabled',
          ],
        },
      ],
    },
  },
});

export const cn = (...classes: ClassValue[]) => {
  return twMerge(clsx(classes));
};
